name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          use-github-cache: true

      - name: Check formatting
        run: lake exe leaner format --check Leaner Main.lean
